
target 'LXStudent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LXStudent

pod ‘UITableView+FDTemplateLayoutCell’
pod ‘YYKit’
pod ‘Mantle’
pod “ReactiveSwift”

end
